// Generated by the devefx compiler. DO NOT EDIT!
package com.binance.account.data.entity.user;

import com.binance.master.utils.StringUtils;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;

/**
 * UserIndex 用户索引表根据user_id 分表
 *
 * @date 2018-01-09 11:49:50
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class UserIndex implements Serializable {

    private static final long serialVersionUID = -7213708453899974656L;
    private Long userId; // 用户id
    private String email; // 登录的账号

    @Override
    public String toString() {
        return StringUtils.objectToString(this);
    }
}
