// Generated by the devefx compiler. DO NOT EDIT!
package com.binance.account.data.entity.user;

import com.binance.master.utils.StringUtils;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * UserInfo 用户信息
 *
 * @date 2018-01-09 11:49:50
 */
@Getter
@Setter
public class UserInfo implements Serializable {

    private static final long serialVersionUID = 6980434842040150016L;
    private Long userId; // 用户Id
    private Long parent; // 主账户
    private Long agentId; // 推荐人
    private BigDecimal agentRewardRatio; // 经纪人返佣比例
    private BigDecimal referralRewardRatio; // 被推荐人(当前userID)返佣比例
    private Long tradingAccount; // 用户交易账户
    private BigDecimal makerCommission; // 被动方手续费
    private BigDecimal takerCommission; // 主动方手续费
    private BigDecimal buyerCommission; // 买方交易手续费
    private BigDecimal sellerCommission; // 卖方交易手续费
    private BigDecimal dailyWithdrawCap; // 单日最大出金总金额
    private Integer dailyWithdrawCountLimit; // 单日最大出金次数
    private BigDecimal autoWithdrawAuditThreshold; // 免审核额度
    private String nickName; // 昵称
    private String nickColor; // 昵称背景色
    private String remark; // 备注
    private String trackSource; // 注册渠道
    private Date updateTime; // 更新时间
    private Date insertTime; // 创建时间
    private Integer tradeLevel;//交易级别
    private Long marginUserId; // margin账户的userid
    private Long fiatUserId; // 主站法币账户的userid
    private BigDecimal dailyFiatWithdrawCap; // 法币单日最大出金总金额
    private BigDecimal singleFiatWithdrawCap; // 法币单次最大出金总金额
    private Long futureUserId;//future账户的userid
    private Long meTradingAccount;//期货撮合引擎的accountid
    private Long futureAgentId;//future返佣推荐id
    @Deprecated
    private BigDecimal trade30btcNumber;//近30天折算BTC交易额。这个字段没有同步
    @Deprecated
    private String tradeAutoStatus;//交易级别自动更新，Y:自动更新，其余不自动更新。这个字段没有同步
    private Long orderConfirmStatus;// 下单确认配置状态

    private Long miningUserId;// 矿池账户的userid
    private String accountType;
    private Long cardUserId;//card账户userId

    private Long deliveryTradingAccount;//期货交割合约撮合引擎的accountId

    @Override
    public String toString() {
        return StringUtils.objectToString(this);
    }
}
