// Generated by the devefx compiler. DO NOT EDIT!
package com.binance.account.vo.security;

import com.binance.account.common.enums.ProtectedStatus;
import com.binance.master.utils.StringUtils;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

/**
 * UserSecurity 用户安全信息
 *
 * @date 2018-01-09 11:49:50
 */
@Getter
@Setter
public class UserSecurityVo implements Serializable {

    private static final long serialVersionUID = -6383538130583482368L;
    private Long userId; // 用户id
    private String email; // 用户邮箱
    private String antiPhishingCode; // 防钓鱼码
    private Integer securityLevel; // 用户安全级别:1:普通,2:身份认证,3:?
    private String mobileCode; // 手机国家编码
    private String mobile; // 手机
    private Integer loginFailedNum; // 当日密码错误次数
    private Date loginFailedTime; // 登录失败日期
    private String authKey; // 谷歌2次验证
    private Date disableTime; // 禁用时间
    private Date unbindTime; // 解绑时间
    private Date deregisterYubikeyTime; //解绑Yubikey时间
    private Date lastLoginTime; // 最后登录时间
    private Date lockEndTime; // 锁定结束时间
    private Date insertTime; // 插入时间
    private Date updateTime; // 更新时间
    private Integer withdrawSecurityStatus;//手动禁用:0:正常;1:禁用
    private Integer withdrawSecurityAutoStatus;//风控禁用:0:正常;1:禁用
    private Integer withdrawSecurityFaceStatus; //提现风控是否需要做人脸识别: 0:不需要做 1: 需要做人脸识别
    private ProtectedStatus protectedStatus; // 用户保护状态

    @Override
    public String toString() {
        return StringUtils.objectToString(this);
    }
}
