// Generated by the devefx compiler. DO NOT EDIT!
package com.binance.account.vo.security;

import java.io.Serializable;
import java.util.Date;

import com.binance.master.utils.StringUtils;

import lombok.Getter;
import lombok.Setter;

/**
 * UserSecurityLog 用户安全日志
 *
 * @date 2018-01-09 11:49:50
 */
@Getter
@Setter
public class UserSecurityLogVo implements Serializable {

    private static final long serialVersionUID = -4717227737145921536L;
    private Long id; //
    private Long userId; // 用户id
    private String ip; // 用户ip
    private String ipLocation; // 用户ip所在位置
    private String clientType; // 客户端类型 ios android web wap
    private String operateType; // 操作类型
    private Date operateTime; // 操作时间
    private String description; // 操作描述
    private String email;//邮箱

    @Override
    public String toString() {
        return StringUtils.objectToString(this);
    }
}
