// Generated by the devefx compiler. DO NOT EDIT!
package com.binance.account.vo.certificate;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * UserCertificate
 *
 * @date 2018-01-09 11:49:50
 */
@Data
public class UserCertificateVo implements Serializable {

    private static final long serialVersionUID = 6799787621272223744L;
    private Long userId; // 用户id
    private String front; // 证件正面
    private String back; // 证件反面
    private String hand; // 手持证件
    private String firstName; //
    private String lastName; //
    private String message; // 消息
    private String lastAuditor; // 最后审核人
    private Byte status; // 0,"审核中" , 1,"通过" 2,"拒绝"
    private String number; // 证件号码
    private Integer type; // 类型:
    private Integer sex; // 性别:
    private String country; // 国家
    private Integer version; // 版本号
    private Date updateTime; // 更新时间
    private Date createTime; 
    private Date insertTime; // 创建时间
	private String email;//邮件

}
