// Generated by the devefx compiler. DO NOT EDIT!
package com.binance.account.data.entity.security;

import com.binance.master.commons.Page;
import com.binance.master.utils.DateUtils;
import com.binance.master.utils.StringUtils;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * UserSecurityLog 用户安全日志
 *
 * @date 2018-01-09 11:49:50
 */
@Getter
@Setter
public class UserSecurityLog extends Page implements Serializable {

    private static final long serialVersionUID = -4717227737145921536L;
    private Long id; //
    private Long userId; // 用户id
    private String ip; // 用户ip
    private String ipLocation; // 用户ip所在位置
    private String clientType; // 客户端类型 ios android web wap
    private String operateType; // 操作类型
    private Long devicePk;      // user_device.id
    private String deviceId;    // 设备指纹ID
    private Date operateTime; // 操作时间
    private String description; // 操作描述
    
    private Date startDate;//起始时间
    private Date endDate;//结束时间
    private String sort;//排序字段
    private String order;//排序
    
    private String email;//邮箱
    //查询参数
    private List<String> operateTypeList;

    @Override
    public String toString() {
        return StringUtils.objectToString(this);
    }

    public UserSecurityLog(){}

    public UserSecurityLog(Long userId, String ip, String ipLocation, String clientType, String operateType, String description){
        this.userId = userId;
        this.ip = ip;
        this.ipLocation = ipLocation;
        this.clientType = clientType;
        this.operateType = operateType;
        this.description = description;
        this.operateTime = DateUtils.getNewUTCDate();   //当前时间
    }

    /**
     * 关联设备信息
     * @param devicePk user_device.id 主键
     * @param deviceId user_device.content.device_id 标识符
     */
    public void touchDevice(Long devicePk, String deviceId){
        this.devicePk = devicePk;
        this.deviceId = deviceId;
    }
}
